name: Release

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # don't cancel, since the commit this flow pushes will trigger it again

permissions: {} # none, since we use a custom app

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@57f3e577827d04134c3d9f2410c8c85768472ec6 # main
    with:
      replace-files: |
        Cargo.lock
        Cargo.toml
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
